In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'the galss of milk',
    'the glass of juice',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the galss of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
one_hot_representation=[one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_representation

[[1103, 4023, 7046, 7262],
 [1103, 5639, 7046, 4931],
 [5453, 2348, 603, 4241, 2325],
 [5453, 2348, 603, 4241, 7027],
 [9597, 1103, 5373, 7046, 3885],
 [4786, 3328, 8000, 4241]]

In [12]:
## word embedding reprsentation layers

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [18]:
sent_length=8 # make every sent length to 8th so that we cantrain model easily
embedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1103 4023 7046 7262]
 [   0    0    0    0 1103 5639 7046 4931]
 [   0    0    0 5453 2348  603 4241 2325]
 [   0    0    0 5453 2348  603 4241 7027]
 [   0    0    0 9597 1103 5373 7046 3885]
 [   0    0    0    0 4786 3328 8000 4241]]


In [19]:
## feature representation
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 410ms/step


array([[[ 0.01115083, -0.00453988, -0.02562132,  0.00835129,
          0.04953319,  0.01888433, -0.00573678,  0.0139866 ,
         -0.03074881,  0.0228608 ],
        [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,
          0.04953319,  0.01888433, -0.00573678,  0.0139866 ,
         -0.03074881,  0.0228608 ],
        [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,
          0.04953319,  0.01888433, -0.00573678,  0.0139866 ,
         -0.03074881,  0.0228608 ],
        [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,
          0.04953319,  0.01888433, -0.00573678,  0.0139866 ,
         -0.03074881,  0.0228608 ],
        [-0.03865929,  0.00101047,  0.02610977,  0.02018711,
          0.02829827, -0.02156898, -0.04528449, -0.01971056,
         -0.01295422, -0.04087235],
        [-0.00943372, -0.04359851,  0.02629979,  0.00578933,
          0.00128517, -0.02631502, -0.027554  , -0.00940776,
         -0.01630551,  0.03745176],
        [-0.02961918, -0.00641654,  0.03013981, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 1103, 4023, 7046, 7262])

In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[ 0.01115083, -0.00453988, -0.02562132,  0.00835129,  0.04953319,
         0.01888433, -0.00573678,  0.0139866 , -0.03074881,  0.0228608 ],
       [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,  0.04953319,
         0.01888433, -0.00573678,  0.0139866 , -0.03074881,  0.0228608 ],
       [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,  0.04953319,
         0.01888433, -0.00573678,  0.0139866 , -0.03074881,  0.0228608 ],
       [ 0.01115083, -0.00453988, -0.02562132,  0.00835129,  0.04953319,
         0.01888433, -0.00573678,  0.0139866 , -0.03074881,  0.0228608 ],
       [-0.03865929,  0.00101047,  0.02610977,  0.02018711,  0.02829827,
        -0.02156898, -0.04528449, -0.01971056, -0.01295422, -0.04087235],
       [-0.00943372, -0.04359851,  0.02629979,  0.00578933,  0.00128517,
        -0.02631502, -0.027554  , -0.00940776, -0.01630551,  0.03745176],
       [-0.02961918, -0.00641654,  0.03013981, -0.04106898, -0.00182911,
        -0.01193376, -0.04287697,  0.01625106